# Generated by Django 3.1.1 on 2020-09-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('name', models.CharField(db_column='NAME', max_length=45, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DISEASE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Incompatibility',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('food_a', models.CharField(db_column='FOOD_A', max_length=45)),
                ('food_b', models.CharField(db_column='FOOD_B', max_length=45)),
                ('description', models.CharField(blank=True, db_column='DESCRIPTION', max_length=100, null=True)),
            ],
            options={
                'db_table': 'INCOMPATIBILITY',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=45, null=True)),
                ('area', models.CharField(blank=True, db_column='AREA', max_length=45, null=True)),
                ('tel', models.CharField(blank=True, db_column='TEL', max_length=45, null=True)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=150, null=True)),
                ('latitude', models.CharField(blank=True, db_column='LATITUDE', max_length=45, null=True)),
                ('longitude', models.CharField(blank=True, db_column='LONGITUDE', max_length=45, null=True)),
                ('category', models.CharField(blank=True, db_column='CATEGORY', max_length=100, null=True)),
                ('menu', models.CharField(blank=True, db_column='MENU', max_length=300, null=True)),
            ],
            options={
                'db_table': 'STORE',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StoreAll',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='NAME', max_length=45, null=True)),
                ('branch', models.CharField(blank=True, db_column='BRANCH', max_length=45, null=True)),
                ('area', models.CharField(blank=True, db_column='AREA', max_length=45, null=True)),
                ('tel', models.CharField(blank=True, db_column='TEL', max_length=45, null=True)),
                ('address', models.CharField(blank=True, db_column='ADDRESS', max_length=100, null=True)),
                ('latitude', models.CharField(blank=True, db_column='LATITUDE', max_length=45, null=True)),
                ('longitude', models.CharField(blank=True, db_column='LONGITUDE', max_length=45, null=True)),
                ('category', models.CharField(blank=True, db_column='CATEGORY', max_length=45, null=True)),
                ('menu', models.CharField(blank=True, db_column='MENU', max_length=200, null=True)),
            ],
            options={
                'db_table': 'STORE_ALL',
                'managed': False,
            },
        ),
    ]
