# Generated by Django 3.1.1 on 2020-09-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_store', '0002_disease_incompatibility_store_storeall'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disease',
        ),
        migrations.DeleteModel(
            name='StoreAll',
        ),
    ]
